#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

start:
    path:     /home
    controller: App\Controllers\HomeController::start

category_list:
      path:     /categoryList
      controller: App\Controllers\GetCategoryListController::getCategoryList

sub_category_list:
      path:     /subcategoryList
      controller: App\Controllers\GetCategoryListController::getSubCategoryList